// Generated by CoffeeScript 1.10.0
(function() {
  var ForkLinter, MultipleCallback, _;

  _ = require('lodash');

  ForkLinter = require('./ForkLinter');

  module.exports = MultipleCallback = (function() {
    function MultipleCallback() {}

    MultipleCallback.prototype.rule = {
      name: 'multiple_callback',
      level: 'error',
      message: 'asdf',
      description: '    '
    };

    MultipleCallback.prototype.lintAST = function(root_node, astApi) {
      var err, fork_linter, i, len, ref;
      this.astApi = astApi;
      fork_linter = new ForkLinter();
      fork_linter.lint(root_node);
      ref = fork_linter.errors;
      for (i = 0, len = ref.length; i < len; i++) {
        err = ref[i];
        this.errors.push(this.astApi.createError(err));
      }
    };

    return MultipleCallback;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
